### ISSUE TITLE
[2.4.2] Getting error "Error in mounted hook"

### ISSUE THREAD

**Issue by archer3cl** [ankurk91/vue-bootstrap-datetimepicker#1]
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 4.17.47
* Vue.js version : 2.2.2
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 2.4.2

**Current behavior**
Clean installation in a non-module environment, setting as docs says, getting the next error:
![screenshot_1](https://user-images.githubusercontent.com/4583932/28190338-0273353c-67f0-11e7-866e-75c05c07efe6.png)

**Expected behavior**
Input should be created

**Minimal reproduction of the problem with instructions**
Clean installation in a non-module environment
Demo of the problem https://jsfiddle.net/Archer3CL/6xjj9vtr/6/

**Comment by ankurk91** [comment]
@archer3cl 
Thanks for reporting.
This should be fixed in v2.4.3.
Try the updated fiddle -
https://jsfiddle.net/0k116tgh/2/
