### ISSUE TITLE
Does Autoclose work ? If so, how do I set it ?

### ISSUE THREAD

**Issue by jdriesen** [ankurk91/vue-bootstrap-datetimepicker#11]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : lastest
* Vue.js version : latest
* Browser name and version : Chrome|Firefox|Safari Chrome
* This package version : lastes
I'm writing '**latest** cause I just installed everything.

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

I don't think it's a bug... it's more about a lack of knowledge from my side...

Thanks in advance for your help,

Johnny

**Comment by ankurk91** [comment]
@jdriesen 
Which feature you are talking about ?
http://eonasdan.github.io/bootstrap-datetimepicker/Options/
There is no such option in api.
Datepicker does autoclose after selecting a date, see GIF
![peek 2017-09-21 17-59](https://user-images.githubusercontent.com/6111524/30695708-c0fc362e-9ef6-11e7-9fdc-25467320f69b.gif)

**Comment by jdriesen** [comment]
mmm ... that's really really weird :)
Mine does not close automatically after selecting a date.
(that's why I was searching for the autoclose option... it seems I got this "idea" from another component)

I will do some further investigation...

BTW... thanks for the quick reply !!

Grtz,
Johnny

**Comment by jdriesen** [comment]
Just a question from my side..
When I use your component with all it's defaults, I see the 'clock' (leads me to the time settings).

Is this 'normal' ?
(I tried several datepicker components the last days, and I guess there are still some 'left-overs' in my project... that's why I'm asking...)

Grtz,
Johnny

**Comment by ankurk91** [comment]
This date picker uses moment js format tokens, it will detect if your have passed time format tokens and will show timepicker automatically

**Comment by ryanwinchester** [comment]
Mine does not autoclose either.

**Comment by ankurk91** [comment]
The datepicker should auto close if user clicks outside.
It is hard to determine whether user has finished selection when the time picker is enabled.
