### ISSUE TITLE
Example package.json file

### ISSUE THREAD

**Issue by jdriesen** [ankurk91/vue-bootstrap-datetimepicker#12]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : lastest
* Vue.js version : latest
* Browser name and version : Chrome
* This package version : latest
Started from scratch, even with a brandnew vue-project via the vue-cli.

**Current behavior**

Can't make it working
**Expected behavior**

Hi @ankurk91 
Can I kindly ask you to give us a working version via a package.json file ?
Whatever I'm trying (copy pasted you example), I'm all the time getting the error "**jQuery is not defined**" (though, I installed jquery via npm install...)

Your help would be highly appreciated.
I've spent several hours to try to make it work.

Thanks in advance,
Johnny (Belgium)

**Comment by ankurk91** [comment]
@jdriesen 
Well, if you are familiar with webpack then instructions can be found in the [readme.md](https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/master/README.md#usage) file.
`package.json` has nothing to do here.
Copy paste my examples wont work in that way.
You have to clone this repo and then you can get examples working.

Here are my quick solution on based on what i understand up to now.
### Webpack
You might be missing this config -
https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/master/webpack.config.dev.js#L71-L75

### Without webpack
It is damn easy, checkout next fiddle
https://jsfiddle.net/ankurk91/zupazg2u/

**Comment by jdriesen** [comment]
Goodmorning, @ankurk91 

Thanks for your reply.
A couple of hours ago, I found the same solution.
(adding a few lines in WebPack did the trick)

Sorry to say, but I can't find a single word about 'webpack" it in your readme file...

I think I did what most users would do when debugging..

- Installing a brandnew Vue project via the Vue CLI
- Adding your project via NPM install..

But I ran into the same probs everytime ... 
Anyway, now it's solved, and I'm happy

Last night, after implementing the Webpack solution, I noticed a small problem when building the project.
More news about it later on today...

(Just as an info ... on your jsfiddle, the datepicker is not closing after selecting a date)

Kind regards & thanks again for your replies & support,

Johnny

**Comment by ankurk91** [comment]
The dateTIMEpicker by default assume that you wants a time picker as well.
You can configure the format in config. DateTIMEpicker will change its UI as per the format you passed in config.
```
format: 'DD/MM/YYYY'
```
Then it should close after selecting the date.
Or you can add a close button on its UI.
```
showClear: true,
showClose: true,
```

FYI: Vue recommands weback and Vue-cli has weback templates to get up and running.
Most of the vue plugins meant to be used in webpack environment.

**Comment by jdriesen** [comment]
Al right.
Got the message :)

Thanks again for your support.

Kind regards,
Johnny
