### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by greevin** [ankurk91/vue-bootstrap-datetimepicker#16]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[X] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 5.4.2
* Vue.js version : 2.4.4
* Browser name and version : Chrome 61.0.3163.100
* This package version : 3.1.1

Sorry for the noob question. How can I change the date format passed to Vue? I've already put the format in the settings, but when choosing a date, it goes with another setting.

`configs: {
      format: 'L',
      locale: document.documentElement.lang
    }
`

Screenshot:
![teste](https://user-images.githubusercontent.com/7833013/31231507-7646fb88-a9bd-11e7-95ac-50112ef9445c.png)

Thanks.

**Comment by ankurk91** [comment]
https://momentjs.com/docs/#/displaying/format/

I have made some examples in this repo
https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/master/examples/App.vue

**Comment by ankurk91** [comment]
Can you share your full code? Html and js part.

**Comment by greevin** [comment]
Yeah, I've looked the examples, but I don't understand why the date format is not accepted.
 
HTML:
`<div class="input-group">}
                    <date-picker v-model="start_date" placeholder="DD/MM/AAAA" :config="configs"></date-picker>
                    <div class="input-group-addon">
                        <span class="fa fa-calendar fa-fw"></span>
                    </div>
                </div>`

VUE:
`data: {
    start_date: null,
    configs: {
      format: 'L',
      locale: document.documentElement.lang
    }
  },`

This is all, for now.

**Comment by greevin** [comment]
Hey, I found a solution for my problem in this link: https://jsfiddle.net/crabbly/xoLwkog9/. 

Thank you for your support. :)
