### ISSUE TITLE
TypeError: this.elem.datetimepicker is not a function

### ISSUE THREAD

**Issue by fagubla** [ankurk91/vue-bootstrap-datetimepicker#17]
**I'm submitting a ...**  (check one with "x")
```
[ X] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 4.17.47
* Vue.js version : 2.4.4
* Browser name and version : Chrome|Firefox
* This package version : 3.1.2

**Current behavior**
Adding it as a component (inside a component file) and it doesn't work. An empty input box shows up, but that's it. Here's the exception I see on the console:

vue.esm.js?65d7:476 [Vue warn]: Error in mounted hook: "TypeError: this.elem.datetimepicker is not a function"

found in
`
---> <DatePicker>

       <DatetimeField> at src/components/core/fields/datetimeField.vue

         <Formu> at src/components/core/form/Formu.vue

           <App> at src/App.vue

             <Root>
`
**Expected behavior**
Should work as described in the documentation

**Minimal reproduction of the problem with instructions**
Follow the documentation. (README.md)

**Comment by ankurk91** [comment]
@fagubla 
Are you using webpack ?
Then you should follow the instructions in readme.
https://github.com/ankurk91/vue-bootstrap-datetimepicker#using-webpack
```js
// webpack.config.js
plugins: [
    new webpack.ProvidePlugin({
      Vue: ['vue/dist/vue.esm.js', 'default'],
      jQuery: 'jquery',
      'window.jQuery': 'jquery',
      $: 'jquery',
      moment: 'moment',
    }),
  ]  
```

**Comment by fagubla** [comment]
@ankurk91  thanks. It's working.

**Comment by restless** [comment]
@ankurk91 Any hints on how to make this work with browserify?

**Comment by ankurk91** [comment]
I have no experience with browserify.
I just found these links,
https://github.com/browserify/browserify/issues/868
https://github.com/thlorenz/browserify-shim

**Comment by rvasoya** [comment]
i'm getting same error and im using vue-cli how to solve it?

**Comment by ankurk91** [comment]
@rvasoya 

I have no experience with vue-cli, always do custom webpack configuration.

I believe you are using some webpack template, but which one ?
https://github.com/vuejs-templates/webpack-simple
https://github.com/vuejs-templates/webpack


Ultimately you need to configure webpack described in [README.md](https://github.com/ankurk91/vue-bootstrap-datetimepicker#using-webpack)

**Comment by restless** [comment]
@ankurk91 Thanks for the answer. Sadly I didn't succeed with that browserify setup, however I had some other priorities so didn't spent too much time on that one - read: maybe it's possible to make this work :D

**Comment by rvasoya** [comment]
i'm using
https://github.com/vuejs-templates/webpack

**Comment by ankurk91** [comment]
You need to edit 
https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.prod.conf.js
Something like this -
https://gist.github.com/anonymous/9417e6dce06acad13ca557460dabd6a3

**Comment by rvasoya** [comment]
solved it by using it inside webpack.base.conf.js.
Thnx
