### ISSUE TITLE
Hide input when inline mode

### ISSUE THREAD

**Issue by lira92** [ankurk91/vue-bootstrap-datetimepicker#18]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Question
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 4.x.x
* Vue.js version : 2.4.2
* Browser name and version : Chrome 61.0
* This package version : 4.0.0

**Current behavior**
How Can I hide the input when use inline option?
![vue-bootstrap-datetimepicker](https://user-images.githubusercontent.com/10679262/31943138-78646566-b8a6-11e7-8eb1-d9cf5892109c.PNG)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
I never though that someone will be using inline mode.
Right now there is no way. 
Let me try if i can adjust component.

**Comment by ankurk91** [comment]
@lira92 
Please update to v4.1.0

**Comment by lira92** [comment]
@ankurk91 thanks, it worked perfectly.
