### ISSUE TITLE
Change the week start day

### ISSUE THREAD

**Issue by matthew-inamdar** [ankurk91/vue-bootstrap-datetimepicker#20]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 4.1.0
* Vue.js version : 2.5.8
* Browser name and version : Chrome 62
* This package version : x.x.x

**Current behaviour**
The start day of the week is always Sunday.

**Expected behaviour**
The ability to add the config option: `weekStart: 1` to specify the starting day of the week (e.g. Monday).

**Minimal reproduction of the problem with instructions**
N/A

**Comment by ankurk91** [comment]
This has been asked previously -
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/670
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/345

This vue component can't support features that [parent repo](https://github.com/Eonasdan/bootstrap-datetimepicker/) dont.
