### ISSUE TITLE
config no update

### ISSUE THREAD

**Issue by gitcoffee** [ankurk91/vue-bootstrap-datetimepicker#21]
update minDate via "methods or computed" from config.minDate NO update!?

**Comment by ankurk91** [comment]
Does it helps?

https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/dadb3b7492cb0b087091537409d3d01731bcf1fe/examples/App.vue#L234-L237

**Comment by kamilzmijowski** [comment]
Hi 
I have same problem. When i'm updating settings by `this.$set(this.endRange, 'minDate', $event.date); ` 
that get no result in ui. Vue isn't  updating module interface. 

Config data are updating in component -> minDate, maxDate 
You can see that when open this example: 
[https://jsfiddle.net/kamil_zmijowski/zupazg2u/157/](url)

I need to do range inputs to my work! Please respond to my by quickly as you can as do that :)

**Comment by ankurk91** [comment]
Checkout this example:
https://jsfiddle.net/w99v77k4/1/
