### ISSUE TITLE
linked picker: config not updated (continue)

### ISSUE THREAD

**Issue by andrii-trush** [ankurk91/vue-bootstrap-datetimepicker#22]
Hello. Your example from #21 not working correctly. 
Steps: 

1. Open "End date" picker
2. Chose date in the "Start date" picker
3. Open again "End date" picker

Actual result:
And you see that days are available, which are before start date

Expected result:
Days have to be not available, which are before start date

**Comment by ankurk91** [comment]
Your issue title says "config not updated" andi I showed you how you can update config dynamically.

**Comment by andrii-trush** [comment]
@ankurk91 Yes. But it does not update config dynamically.
![a](https://user-images.githubusercontent.com/14265776/34292192-80ee55ee-e708-11e7-85fa-5c1ce28e095b.gif)

**Comment by ankurk91** [comment]
It is working fine for me.
![peek 2017-12-22 16-59](https://user-images.githubusercontent.com/6111524/34296685-b21cca2a-e739-11e7-90ec-4cffba94b1c4.gif)
Configs are being updated.
 It is upto you; how to restrict user from selecting dates.

**Comment by andrii-trush** [comment]
@ankurk91 If you select End date first - it works incorrect (((

**Comment by ankurk91** [comment]
You meant I need to select end date first and then start date?
OR
You are saying that I have selected end date first in my GIF.

**Comment by andrii-trush** [comment]
> You meant I need to select end date first and then start date?

Yes. Look at my gif. You see an error )))

**Comment by ankurk91** [comment]
I got your issue, now.
In [this](https://jsfiddle.net/w99v77k4/1/) example, start date has a `minDate` of today and if we select an end date before todays date; the "start date" input field locks down.
This issue can be fixed by setting `minDate` on end date field.
Check the updated fiddle.
https://jsfiddle.net/w99v77k4/5/
![peek 2017-12-22 18-43](https://user-images.githubusercontent.com/6111524/34299273-19921062-e748-11e7-9672-1d03b7deacfd.gif)

My statement will remain same -
> It is upto you; how to restrict user from selecting dates.

**Comment by andrii-trush** [comment]
@ankurk91 Ok. Click step by ste/p:
1.  Select start date 28/12/2017
2. Select end date 30/12/2017
3 Select start date 23/12/2017

In end date you cannot select from 24/12 to 27/12

Other issue:
1.  Select start date 25/12/2017
2. Select end date 30/12/2017
3 Select start date 27/12/2017

You can select 25/12 and 26/12 as end date, but your start date is 27/12

**Comment by ankurk91** [comment]
I was able to reproduce your first case.
I found that Vue.js can is not detecting change in `minDate` because it is moment js object.
I will keep you posted, if i found a solution.

**Comment by andrii-trush** [comment]
@ankurk91 Thanks. Will wait, because i really require this issue )))

**Comment by ankurk91** [comment]
@andrii-trush 
This issue has been fixed in v4.1.1
Thanks for reporting and steps to re-produce.
