### ISSUE TITLE
Import into uiv

### ISSUE THREAD

**Issue by lgnap** [ankurk91/vue-bootstrap-datetimepicker#26]
Hello,

Could we take your work to import it into https://github.com/wxsms/uiv ?
It's better to have all work integrated in one place.

Thanks by advance,

**Comment by ankurk91** [comment]
@lgnap 
Thanks for connecting. Before you import; do consider these things -

* This vue component is just a wrapper of an existing [jQuery based plugin](http://eonasdan.github.io/bootstrap-datetimepicker/).
* It is not pure Vue.js, requires jQuery and moment.js
* The original [library](https://github.com/Eonasdan/bootstrap-datetimepicker) is no longer maintained but still works well.
* Does not support bootstrap 4

If you are OK with these, feel free to import any piece of code from this component to yours.
The [MIT license](https://choosealicense.com/licenses/mit/) allows anyone to copy and modify the code for their needs.
