### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by GotaloveCode** [ankurk91/vue-bootstrap-datetimepicker#27]
**I'm submitting a Feature request**  
Is it possible to have the datetimepicker glyphicon added to a datepicker with the on change method added.

**Comment by ankurk91** [comment]
Can you elaborate more about where you want to add font icon?

**Comment by GotaloveCode** [comment]
I mean like how its done in bootstrap with the usual datetimepicker like below:
`<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
    </div>
</div>`

**Comment by ankurk91** [comment]
Something like this
https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/4eee1607c10d275abb43e7884aa31033de3ebeb5/examples/App.vue#L41

**Comment by GotaloveCode** [comment]
Thanks for the quick response.Highly appreciated.Will attempt to replicate this and see if it behaves as expected.
