### ISSUE TITLE
Bug or feature with maxDate config property?

### ISSUE THREAD

**Issue by KorzhovDmitry** [ankurk91/vue-bootstrap-datetimepicker#29]
**I'm submitting a Bug report** 

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 4.1.2
* Vue.js version : 2.4.4
* Browser name and version : Chrome 64
* This package version : latest

**Current behavior**
When set config option "maxDate" to current date like 
``
maxDate: new Date()
``
button "Go to today" dont change date to current date.

**Expected behavior**
Button "Go to today" change date to current.

**Way to avoid this behavior**
If i set "maxDate" like 
``
maxDate: new Date().setHours(23, 59, 59, 999)
``
button works fine, but i think its a tricky way. May be need do checks in plugin?

**Comment by ankurk91** [comment]
What if you pass `moment()` as maxDate ?

Can you fork this jsfiddle and setup your code there ?
https://jsfiddle.net/ankurk91/zupazg2u/

**Comment by KorzhovDmitry** [comment]
I create sample with comments. [https://jsfiddle.net/daruqe05/10/](url)

**Comment by ankurk91** [comment]
This is not working in original datepicker.
Here is the jsfiddle that is not using vue.js

https://jsfiddle.net/mk9k1dpd/2/
