### ISSUE TITLE
Not Visible

### ISSUE THREAD

**Issue by bobbygerez** [ankurk91/vue-bootstrap-datetimepicker#3]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 4.x.x
* Vue.js version : 2.x.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**
It doesn't show if you after clicking.

**Expected behavior**
Show the datetimepicker

**Minimal reproduction of the problem with instructions**
 I have a modal and inside the modal is the `<date-picker v-model="date"></date-picker>` but it doesn't show. See screenshot... is it because of z-index. TY
![untitled](https://user-images.githubusercontent.com/10149942/28763391-2f681cac-75f0-11e7-9f0b-deb0bb0da1d8.png)

**Comment by ankurk91** [comment]
This issue should be reported on -
https://github.com/Eonasdan/bootstrap-datetimepicker/issues

This Vue component has nothing to do with UI .
