### ISSUE TITLE
AM/PM not working

### ISSUE THREAD

**Issue by sherlyseptiani** [ankurk91/vue-bootstrap-datetimepicker#31]
**I'm submitting a ...**  (check one with "x")
```
[ x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Current behavior**
In your JS Fiddle and in my implementation, the AM-PM doesn't change anything on the data.
How to make it to 24 hour format? For example if we choose 4 PM then it will be 16:00 because now we cannot differentiate between AM and PM

**Minimal reproduction of the problem with instructions**
On your JS fiddle

**Comment by ankurk91** [comment]
The datepicker uses moment js formats
https://momentjs.com/docs/#/displaying/format/
so you can pass the suitable format in configs.
