### ISSUE TITLE
Styiling issues with Laravel & Webpack

### ISSUE THREAD

**Issue by smholsen** [ankurk91/vue-bootstrap-datetimepicker#32]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[X] Other, please describe
```
Hi!
Thank you very much for hosting this repo.
I am having some troubles trying to use the component however. 
![image](https://user-images.githubusercontent.com/1721346/39211507-192cedf2-480c-11e8-9c1d-fa1fe7ebeb2d.png)
I see that the Glyphicons does not appear, but the functionality within the component works fine. Do you have any ideas on what might be wrong here? 
I am using this with Laravel and Vue, and importing these dependencies in the script part of the parent vue component.

     // Import required dependencies
    import datePicker from 'vue-bootstrap-datetimepicker';
    import 'bootstrap/dist/css/bootstrap.css';
    import 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css';

Sorry if this is not the correct place to post this.

**Comment by smholsen** [comment]
Solved the missing glyphicons by editing the configs to desired icons from fontawesome icons.
The styling issues I am guessing might come from some of my own rules, I have not gotten to debuggind this yet. 
However there is still an issue when having time in to addition to the date. 
![image](https://user-images.githubusercontent.com/1721346/39213356-a58a3c32-4811-11e8-960c-0f9595e3c676.png)

Clicking the click icon opens the time picker correctly, but attempting to click back does not swap the view back to the calendar.
![image](https://user-images.githubusercontent.com/1721346/39213530-1fb45eb6-4812-11e8-8256-7857de72c077.png)

**Comment by ankurk91** [comment]
You can check my webpack configs

https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/8344b915c67e7ee6233c47ad559701c314cf4802/webpack.config.dev.js#L49-L50

**Comment by smholsen** [comment]
Thank you very much :) 
I will get back to debuggibg this later today, and will update the thread with my findings.
I'll also check the version no. then.

**Comment by smholsen** [comment]
Yeah, so the issue was of course that I was using the newest version of bootstrap instead of using version 3 :) Changing to bootstrap 3 fixed the issue. 
Do you think you might make a Vue wrapper for a v4 version in the future? 
e.g. https://github.com/pingcheng/bootstrap4-datetimepicker or https://tempusdominus.github.io/bootstrap-4/

**Comment by ankurk91** [comment]
@smholsen 
I will give it a try.

Meanwhile you may wan to switch to -
https://github.com/ankurk91/vue-flatpickr-component
that does not require any css framework.

**Comment by smholsen** [comment]
Thank you very much :)
