### ISSUE TITLE
[bug] v-model parameter must be one of [null, string, moment or Date]

### ISSUE THREAD

**Issue by cyzeng-Luca** [ankurk91/vue-bootstrap-datetimepicker#4]
**I'm submitting a ...**  (check one with "x")
```
[ x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 4.17.47
* Vue.js version : 2.4.2
* Browser name and version : Chrome
* This package version : 2.4.3

**Current behavior**

![image](https://user-images.githubusercontent.com/25954683/28908453-591b6794-7856-11e7-8512-1936b42de683.png)
![image](https://user-images.githubusercontent.com/25954683/28908591-11e766ba-7857-11e7-9bbe-45ec2eda37f8.png)

i set config  `showClear: true`, but the callback `return e.date = false ` ,when i click it on trash icon , the v-model parameter must be one of [null, string, moment or Date]" . it return false in fact

**Expected behavior**
return null or ''

**Comment by ankurk91** [comment]
This has been fixed in v3.0.0
