### ISSUE TITLE
how to config linked pickers in from

### ISSUE THREAD

**Issue by hx425072624** [ankurk91/vue-bootstrap-datetimepicker#42]

**Comment by ankurk91** [comment]
This is already in examples

https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/fe6ee359c7bfd8a3ccca5150cb9fcafc907eeafb/examples/App.vue#L101-L115

https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/fe6ee359c7bfd8a3ccca5150cb9fcafc907eeafb/examples/App.vue#L278-L284
