### ISSUE TITLE
Date range 

### ISSUE THREAD

**Issue by EugeneBalabai** [ankurk91/vue-bootstrap-datetimepicker#43]
**Tell about your platform**
* [pc-bootstrap4-datetimepicker](https://github.com/pingcheng/bootstrap4-datetimepicker) : 5.0.0 beta 2
* Vue.js version : 2.5.17
* Browser name and version : Chrome 68.0.3440.106
* This package version :  latest

**Problem**
I want to use 2 datepicker for date range. But I have error `n.maxDate.isBefore is not a function` when I select one of date(begin or end of range)
I use Option as Computed property, max and min date is Computed property too

My code https://jsfiddle.net/jkgs2c8o/16/

Where is problem?

**Comment by ankurk91** [comment]
Someone asked same question today -
https://github.com/ankurk91/vue-bootstrap-datetimepicker/issues/42

You should use `@dp-change`.

**Comment by EugeneBalabai** [comment]
Thanks

If I use inline mode for datepicker, `@dp-change` is very slowly and I have some trouble because of this.
Example https://jsfiddle.net/w99v77k4/29/ 
Is there a way to fix this? or another way to do date range

**Comment by ankurk91** [comment]
I see it is slow.
Unfortunately there is nothing I can do with it.
This Vue component is using a jQuery based plugins behind the scenes.
The underlying library has been abondended by the maintainer.

I am also going to stop development on this package soon.
There is nothing left with this package.
