### ISSUE TITLE
5.0.0-beta.2: Problems with locale: de

### ISSUE THREAD

**Issue by doncatnip** [ankurk91/vue-bootstrap-datetimepicker#44]
The script hangs when trying to select a date before 2012. Another weird behaviour: type in 11.11.11 11:11 and you'll notice it changing to 20.11.2011 20:11 and you'll be unable to select a date before 20.11 and a time before 20:xx.

**Comment by ankurk91** [comment]
It works fine for me.

![screen23](https://user-images.githubusercontent.com/6111524/44096326-a1af0a90-9ff8-11e8-80ce-b979fe8e9af0.gif)

What is your source?

**Comment by ankurk91** [comment]
https://jsfiddle.net/ankurk91/01407frf/

**Comment by doncatnip** [comment]
Have you tried locale: de ?

**Comment by ankurk91** [comment]
Why should i?
You should report this to parent library.

**Comment by doncatnip** [comment]
Because it appears to be working in the parent library.

**Comment by ankurk91** [comment]
Can you setup a jsfiddle demonstrating the issue
