### ISSUE TITLE
How to set `keyBinds` ?

### ISSUE THREAD

**Issue by francoismassart** [ankurk91/vue-bootstrap-datetimepicker#45]
**I'm submitting a ...**
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Question
```

**Tell about your platform**
* [pc-bootstrap4-datetimepicker](https://github.com/pingcheng/bootstrap4-datetimepicker) : 4.17.50
* Vue.js version : 2.5.17
* Browser name and version : Chrome
* This package version : [JSFiddle demo version](https://jsfiddle.net/ankurk91/01407frf/)

**Question**
I'd like to disable the usage of the keyboard arrows to change the date because I prefer letting the user move inside the text content of the `input`.
I know it is possible to do so by overwriting the value of `keyBinds`.
[I did it in a codepen using the jQuery version](https://codepen.io/fma/pen/KxmdqQ), but I don't know how to reproduce this using the version made in vuejs...
How to overwrite `keyBinds` ?

**Minimal reproduction of the problem with instructions**
1. Open the [JSFiddle demo for vue](https://jsfiddle.net/ankurk91/01407frf/)
2. Click inside the field
3. Pick any date
4. Press any arrow from the keyboard (left, top, right or bottom)
5. The date value changes, I'd like to avoid this behavior

Thank you for your help

**Comment by ankurk91** [comment]
This is not my concern.

Check this page if you find any information.
http://eonasdan.github.io/bootstrap-datetimepicker/Options/
