### ISSUE TITLE
Error "t.datetimepicker is not a function"

### ISSUE THREAD

**Issue by archer3cl** [ankurk91/vue-bootstrap-datetimepicker#5]
**I'm submitting a ...**  (check one with "x")
```
[ X ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* eonasdan-bootstrap-datetimepicker version : 4.17.47
* Vue.js version : 2.4.2
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 3.0.0

**Current behavior**
Plugin is not working on module environment, console shows Error "t.datetimepicker is not a function"

**Expected behavior**
Plugin should show on module environment

**Minimal reproduction of the problem with instructions**
Clean installation in webpack module. 
```javascript
// at app.js
import moment from 'moment';
import datePicker from 'vue-bootstrap-datetimepicker';
import 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css';
Vue.use(datePicker);

const app = new Vue({
    el: '#app',
    components: {
        datePicker
    }
    data: function(){
      return { testdate: moment() }
    }
});
```
```html
// at index.html
<body>
	<div id="app">
             <date-picker v-model="testdate"></date-picker>
        </div>
</body>
```

error in console
![image](https://user-images.githubusercontent.com/4583932/29483995-0b4e73c2-847b-11e7-9532-e3eecc601e21.png)

**Comment by ankurk91** [comment]
Are you sure you have jQuery installed ?
jQuery not gets automatically installed because of [peerDependencies](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/package.json#L8)

**Tip** When you specify -
```
Vue.use(datePicker);
```
It means you are registering a global component, so you no need to specify local component.

I have setup  a jsfiddle demo for you -
https://jsfiddle.net/ankurk91/zupazg2u/4/

You can also take a look at [examples](https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/master/examples/App.vue) and my [webpack.config](https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/master/webpack.config.dev.js)
Possibly it webpack configuration issue.

**Comment by archer3cl** [comment]
After testing at webpackbin i can implement your plugin without trouble. Maybe is as you say a webpack configuration issue

**Comment by ankurk91** [comment]
May be this can fix this ->
https://github.com/ankurk91/vue-bootstrap-datetimepicker/blob/master/webpack.config.dev.js#L71-L75
Feel free to re-open :smile:

**Comment by TholthoeunChansovann** [comment]
Hi @ankurk91 it not work for me also it show me some error like this " Uncaught ReferenceError: datePicker is not defined".

**Comment by TholthoeunChansovann** [comment]
i'm already import all this in my app.js
import datePicker from 'vue-bootstrap-datetimepicker';
import 'bootstrap/dist/css/bootstrap.css';
import 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css';
Vue.use(datePicker);

**Comment by ankurk91** [comment]
@TholthoeunChansovann
Have you configured webpack ?

**Comment by TholthoeunChansovann** [comment]
@ankurk91 yes already i configured on webpage.mix.js

**Comment by ankurk91** [comment]
Thats strange, it would be helpful if can share a minimal reproduction of the issue on a github repo.

**Comment by TholthoeunChansovann** [comment]
i try use all this code on app.js
import datePicker from 'vue-bootstrap-datetimepicker';
import 'bootstrap/dist/css/bootstrap.css';
import 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css';
Vue.use(datePicker);

and use this code at other components
<date-picker v-model="date" :config="config"></date-picker>

**Comment by ankurk91** [comment]
Sorry, This wont help.

**Comment by TholthoeunChansovann** [comment]
@ankurk91 Thank for help now it work.
