### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by boscho87** [ankurk91/vue-bootstrap-datetimepicker#7]
**I'm submitting a 
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ X] Other, please describe
```
How can i change the date format ?

**Comment by ankurk91** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format

This date-picker follows moment.js format tokens.

**Comment by boscho87** [comment]
can you add an example... i dont know where i need to put the config proberties

**Comment by ankurk91** [comment]
Examples can be found in **examples** folder of repo.
Essentially you can pass any config property documented in above given link.
