### ISSUE TITLE
automatically sets current datetime as a value but i want to set datetime only after picked from datetime picker.

### ISSUE THREAD

**Issue by DeepakAryal** [ankurk91/vue-bootstrap-datetimepicker#8]

**Comment by ankurk91** [comment]
Can you write some more words explaining your issue?

**Comment by DeepakAryal** [comment]
i have used this in input field. when i click on input field, datetime picker opens and it immediately fills the input field with current datetime, which i don't want to set. i want to set only after datetime picked from datetime picker. is it possible or not?

**Comment by ankurk91** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#usecurrent
